config/routes.rb
Rails.application.routes.draw do
  get 'shopping_carts/index', to: "shopping_carts#index"
  resources :shopping_cart
  get 'orders/complete', to: "orders#complete", as: 'orders_complete'
  get 'orders/cancel'

  get 'orders/:product_id', to: "orders#new", as: "new_order"
  resources :orders
  get 'products/index', to: "products#index"
  post ':user_id/products', to: "products#create", as: "create_product"
  resources :products
  resources :models
  devise_for :users


  root 'pages#index'

end

app/models/ability.rb
class Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="My portfolio"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/6e780ffe51.js"></script>
  </head>

  <body>
    <%= flash[:error] %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/products/_navbar.html.erb
<section class="container">
  <nav class="navbar level section has-text-right has-background-primary" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <div class="columns">
        <div class="column is-one-quarter">
          <%= link_to 'HOME', root_path %>
        </div>
        <div class="column is-one-quarter">
          <%= link_to 'PRODUCTS', products_index_path %>
        </div>
        <div class="column is-one-quarter">
          <%= link_to '<i class="fas fa-user-plus"></i>'.html_safe, new_user_registration_path, class: "button is-info is-rounded" %>
        </div>
        <div class="column is-one-quarter">
          <%= link_to '<i class="fas fa-sign-in-alt"></i>'.html_safe, new_user_session_path, class: "button is-info is-rounded" %>
        </div>
        <div class="column is-one-quarter">
          <%=link_to '<i class="fas fa-sign-out-alt"></i>'.html_safe, destroy_user_session_path, method: 'delete', class: "button is-warning is-rounded" %>
        </div>
      </div>
    </div>
  </nav>
</section>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render partial: 'form' %>
<%= link_to 'Back', products_index_path %>